[frangiclave]

BASE_URL = "http://localhost:5000"

DEBUG = false

GAME_DIRECTORY = "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Cultist Simulator\\"

IMAGES_DIRECTORY = "images"

READ_ONLY = false
